[package]
name = "rust-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.5"
bevy = "0.7"
heron = { version = "3.1.0", default-features = false, features = ["2d"] }